/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JSplitPane;
import model.DoctorDirectory;
import model.Hospital;
import model.HospitalDirectory;
import model.Patient;
import model.PatientDirectory;
import model.Person;
import model.PersonDirectory;

/**
 *
 * @author Lenovo
 */
public class HospitalDetails extends javax.swing.JPanel {
    JSplitPane splitPanel;
    HospitalDirectory hospitalDirectory;
    PersonDirectory personDirectory;
    DoctorDirectory doctorDirectory;
    PatientDirectory patientDirectory;

    /**
     * Creates new form HospitalDetails
     */
    public HospitalDetails(JSplitPane splitPanel, HospitalDirectory hospitalDirectory, PersonDirectory personDirectory,
            DoctorDirectory doctorDirectory, PatientDirectory patientDirectory) {
        initComponents();
        this.splitPanel = splitPanel;
        this.hospitalDirectory = hospitalDirectory;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        hospitalHeading = new javax.swing.JLabel();
        hospitalIdLabel = new javax.swing.JLabel();
        hospitalIdInput = new javax.swing.JTextField();
        communityInput = new javax.swing.JTextField();
        cityInput = new javax.swing.JTextField();
        communityLabel = new javax.swing.JLabel();
        cityLabel = new javax.swing.JLabel();
        hospitalNameLabel = new javax.swing.JLabel();
        hospitalNameInput = new javax.swing.JTextField();
        specialityLabel = new javax.swing.JLabel();
        specialityInput = new javax.swing.JTextField();
        viewButton = new javax.swing.JButton();
        importButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();

        hospitalHeading.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        hospitalHeading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hospitalHeading.setText("Add Hospital Details");

        hospitalIdLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        hospitalIdLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        hospitalIdLabel.setText("Hospital ID:");

        communityLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        communityLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        communityLabel.setText("Community:");

        cityLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cityLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        cityLabel.setText("City:");

        hospitalNameLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        hospitalNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        hospitalNameLabel.setText("Hospital Name:");

        specialityLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        specialityLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        specialityLabel.setText("Speciality:");

        viewButton.setText("View");
        viewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewButtonActionPerformed(evt);
            }
        });

        importButton.setText("Import");
        importButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                importButtonActionPerformed(evt);
            }
        });

        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(243, 243, 243)
                        .addComponent(hospitalHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cityLabel)
                            .addComponent(hospitalIdLabel)
                            .addComponent(hospitalNameLabel)
                            .addComponent(communityLabel)
                            .addComponent(specialityLabel))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(specialityInput, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hospitalIdInput, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hospitalNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cityInput, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(communityInput, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(saveButton)
                                .addGap(62, 62, 62)
                                .addComponent(viewButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(importButton)))))
                .addContainerGap(165, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(hospitalHeading)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(hospitalIdLabel)
                        .addGap(18, 18, 18)
                        .addComponent(hospitalNameLabel)
                        .addGap(18, 18, 18)
                        .addComponent(cityLabel))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hospitalIdInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(hospitalNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(cityInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(communityLabel)
                    .addComponent(communityInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(specialityInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(specialityLabel))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewButton)
                    .addComponent(importButton)
                    .addComponent(saveButton))
                .addContainerGap(130, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:
       if(!isInteger(hospitalIdInput.getText()))
       {
        JOptionPane.showMessageDialog(this, "Hospital Id Entered should be Integer");
       }
       else if(hospitalIdInput.getText().equals("")){
           JOptionPane.showMessageDialog(this, "Hospital Id should not be empty");
       }
       else if(hospitalNameInput.getText().equals(""))
       {
           JOptionPane.showMessageDialog(this, "Name Field is empty");
       }
       else if(cityInput.getText().equals(""))
       {
        JOptionPane.showMessageDialog(this, "City Field is empty");
       }
       else if(communityInput.getText().equals(""))
       {
        JOptionPane.showMessageDialog(this, "Community Field is empty");
       }
       else if(specialityInput.getText().equals(""))
       {
        JOptionPane.showMessageDialog(this, "Speciality Field is empty");
       }
       else
       {
           int t=0;
        for(Hospital pt: hospitalDirectory.getHospitalDirectory())
        {
            if(pt.getHospitalId()==Integer.parseInt(hospitalIdInput.getText()))
                t++;
        }
        if(t==0)
        {
            String hospitalName = hospitalNameInput.getText();
            int hospitalId = Integer.parseInt(hospitalIdInput.getText());
            String speciality = specialityInput.getText();
            String city = cityInput.getText();
            String community = communityInput.getText();

            Hospital p = hospitalDirectory.addNewHospital();
            p.setHospitalId(hospitalId);
            p.setHospitalName(hospitalName);
            p.setSpeciality(speciality);
            p.setCity(city);
            p.setCommunity(community);

            JOptionPane.showMessageDialog(this, "Hospital Details Saved");

            hospitalNameInput.setText("");
            hospitalIdInput.setText("");
            specialityInput.setText("");
            cityInput.setText("");
            communityInput.setText("");
       } else {
            JOptionPane.showMessageDialog(this, "This hopital ID is already used");
        }
       }
    }//GEN-LAST:event_saveButtonActionPerformed

    private void importButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_importButtonActionPerformed
        // TODO add your handling code here:
        JFileChooser file = new JFileChooser();
        file.setCurrentDirectory(new File(System.getProperty("user.home")));
        int result = file.showSaveDialog(null);
        if(result == JFileChooser.APPROVE_OPTION){
            File selectedFile = file.getSelectedFile();
            String path = selectedFile.getAbsolutePath();
            String line = "";
            try{
                BufferedReader br = new BufferedReader(new FileReader(path));
                while ((line = br.readLine()) != null) {
                    String [] values = line.split(",");   
                    int hospitalId = Integer.parseInt(String.valueOf(values[0]));
                    String hospitalName = String.valueOf(values[1]);
                    String hospitalCity = String.valueOf(values[2]);
                    String hospitalCommunity = String.valueOf(values[3]);
                    String hospitalSpeciality = String.valueOf(values[4]);
                    Hospital pr = hospitalDirectory.addNewHospital();
                    pr.setHospitalId(hospitalId);
                    pr.setHospitalName(hospitalName);
                    pr.setCommunity(hospitalCommunity);
                    pr.setCity(hospitalCity);
                    pr.setSpeciality(hospitalSpeciality);
                }
            } catch(FileNotFoundException e){
                e.printStackTrace();
            } catch (IOException e) {
                e.printStackTrace();
                }
        }
    }//GEN-LAST:event_importButtonActionPerformed

    private void viewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewButtonActionPerformed
        // TODO add your handling code here:
        ViewHospital viewHospitalDetails = new ViewHospital(splitPanel, hospitalDirectory, null, personDirectory, doctorDirectory,patientDirectory);
        splitPanel.setRightComponent(viewHospitalDetails);
    }//GEN-LAST:event_viewButtonActionPerformed


    private static boolean isInteger(String s) {
    try { 
        Integer.parseInt(s); 
    } catch(NumberFormatException e) { 
        return false; 
    } catch(NullPointerException e) {
        return false;
    }
    // only got here if we didn't return false
    return true;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cityInput;
    private javax.swing.JLabel cityLabel;
    private javax.swing.JTextField communityInput;
    private javax.swing.JLabel communityLabel;
    private javax.swing.JLabel hospitalHeading;
    private javax.swing.JTextField hospitalIdInput;
    private javax.swing.JLabel hospitalIdLabel;
    private javax.swing.JTextField hospitalNameInput;
    private javax.swing.JLabel hospitalNameLabel;
    private javax.swing.JButton importButton;
    private javax.swing.JButton saveButton;
    private javax.swing.JTextField specialityInput;
    private javax.swing.JLabel specialityLabel;
    private javax.swing.JButton viewButton;
    // End of variables declaration//GEN-END:variables
}
