/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import javax.swing.JSplitPane;
import model.HospitalDirectory;
import model.PersonDirectory;
import model.DoctorDirectory;
import model.PatientDirectory;

/**
 *
 * @author Lenovo
 */
public class LoginDoctor extends javax.swing.JPanel {
    JSplitPane splitPanel;
    HospitalDirectory hospitalDirectory;
    PersonDirectory personDirectory;
    DoctorDirectory doctorDirectory;
    PatientDirectory patientDirectory;

    /**
     * Creates new form LoginDoctor
     */
    public LoginDoctor(JSplitPane splitPanel, HospitalDirectory hospitalDirectory, PersonDirectory personDirectory,DoctorDirectory doctorDirectory,PatientDirectory patientDirectory) {
        initComponents();
        this.splitPanel = splitPanel;
        this.patientDirectory = patientDirectory;
        this.personDirectory = personDirectory;
        this.doctorDirectory = doctorDirectory;
        this.hospitalDirectory = hospitalDirectory;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        doctorLoginButton = new javax.swing.JButton();
        systemAdminLoginButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        doctorLoginButton.setText("Login as Doctor");
        doctorLoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doctorLoginButtonActionPerformed(evt);
            }
        });

        systemAdminLoginButton.setText("Login as System Admin");
        systemAdminLoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                systemAdminLoginButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Doctor Details");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(245, 245, 245)
                        .addComponent(doctorLoginButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(222, 222, 222)
                        .addComponent(systemAdminLoginButton)))
                .addContainerGap(220, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(127, 127, 127)
                .addComponent(systemAdminLoginButton)
                .addGap(56, 56, 56)
                .addComponent(doctorLoginButton)
                .addContainerGap(153, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void systemAdminLoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_systemAdminLoginButtonActionPerformed
        // TODO add your handling code here:
        AdminDoctor loginDoctor = new AdminDoctor(splitPanel, personDirectory, doctorDirectory, patientDirectory, hospitalDirectory);
        splitPanel.setRightComponent(loginDoctor);
    }//GEN-LAST:event_systemAdminLoginButtonActionPerformed

    private void doctorLoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doctorLoginButtonActionPerformed
        // TODO add your handling code here:
        DoctorLogin loginDoctor = new DoctorLogin(splitPanel, personDirectory, doctorDirectory, patientDirectory, hospitalDirectory);
        splitPanel.setRightComponent(loginDoctor);
    }//GEN-LAST:event_doctorLoginButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton doctorLoginButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton systemAdminLoginButton;
    // End of variables declaration//GEN-END:variables
}
